apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mercure.fullname" . }}
  labels:
    {{- include "mercure.labels" . | nindent 4 }}
data:
  debug: "{{ if .Values.debug }}debug{{ end }}"
  publisher-jwt-alg: {{ .Values.jwt.publisher.alg | quote }}
  subscriber-jwt-alg: {{ .Values.jwt.subscriber.alg | quote }}
