apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mercure.fullname" . }}
  labels:
    {{- include "mercure.labels" . | nindent 4 }}
type: Opaque
data:
  transport-url: {{ .Values.transportURL | b64enc | quote }}
  publisher-jwt-key: {{ .Values.jwt.publisher.key | default (randAlphaNum 40) | b64enc | quote }}
  subscriber-jwt-key: {{ .Values.jwt.subscriber.key | default (randAlphaNum 40) | b64enc | quote }}
  extra-directives: {{ .Values.extraDirectives | b64enc | quote }}
